: Ion channel activation segregation -- Generated by BMTools (https://github.com/tjbanks/bmtools)
: based on the paper "Distinct Current Modules Shape Cellular Dynamics in Model Neurons" (2016)

NEURON {
	SUFFIX casseg
	USEION ca READ eca WRITE ica
	RANGE gbar, g
	RANGE jainf, kinf, jatau, ktau
	RANGE ica
	RANGE javhalf, jak, jaseg
} 

UNITS {
    (mA) =  (milliamp)
    (mV) =  (millivolt)
}
PARAMETER {
	gbar (siemens/cm2)
	javhalf = 33.0
	jak = -8.1
	jaseg = -99
}

ASSIGNED {
    v (mV)
    eca (mV)
    ica (mA/cm2)
    jainf
    kinf
    jatau (ms)
    ktau (ms)
    g (siemens/cm2)
}
STATE {
    ja
    k
}
BREAKPOINT {
    SOLVE states METHOD cnexp
    g = gbar * ja * ja * ja * k
    ica = g * (v - eca)
}
INITIAL {
    rate(v)
    ja = jainf
    k = kinf
}
DERIVATIVE states{
	rate(v)
	jasegment(v)
	ja' = (jainf - ja) / jatau
	k' = (kinf - k) / ktau
}

PROCEDURE rate(v){
	UNITSOFF
	jainf = (1.0) / (1 + (exp((v + javhalf) / (jak))))
	jatau = 2.8 + 14.0 / ((exp((v + 27.0) / (10.0))) + (exp((v + 70.0) / (-13.0))))
	kinf = 1.0 / (1.0 + (exp((v + 60.0) / (6.2))))
	ktau = (120.0 + 300.0 / ((exp((v + 55.0) / (9.0))) + (exp((v + 65) / (-16.0)))))
	UNITSON
}

: Segmentation functions

PROCEDURE jasegment(v){
	if (v < jaseg){
		jainf = 0
	}
}
