: Ion channel activation segregation -- Generated by BMTools (https://github.com/tjbanks/bmtools)
: based on the paper "Distinct Current Modules Shape Cellular Dynamics in Model Neurons" (2016)

NEURON {
	SUFFIX catseg
	USEION ca READ eca WRITE ica
	RANGE gbar, g
	RANGE uinf, zinf, utau, ztau
	RANGE ica
	RANGE uvhalf, uk, useg
} 

UNITS {
    (mA) =  (milliamp)
    (mV) =  (millivolt)
}
PARAMETER {
	gbar (siemens/cm2)
	uvhalf = 27.1
	uk = -7.2
	useg = -99
}

STATE {
    u
    z
}
ASSIGNED {
    v (mV)
    eca (mV)
    ica (mA/cm2)
    uinf
    zinf
    utau (ms)
    ztau (ms)
    g (siemens/cm2)
}
BREAKPOINT {
    SOLVE states METHOD cnexp
    g = gbar * u * u * u * z
    ica = g * (v - eca)
}
INITIAL {
    rate(v)
    u = uinf
    z = zinf
}
DERIVATIVE states{
	rate(v)
	usegment(v)
	u' = (uinf - u) / utau
	z' = (zinf - z) / ztau
}

PROCEDURE rate(v){
	UNITSOFF
	uinf = 1.0 / (1.0 + (exp((v + uvhalf) / (uk))))
	utau = (43.4 - 42.6 / (1.0 + (exp((v + 68.1) / (-20.5)))))
	zinf = 1.0 / (1.0 + (exp((v + 32.1) / (5.5))))
	ztau = (210 - 179.6 / (1.0 + (exp((v + 55) / (-16.9)))))
	UNITSON
}

: Segmentation functions

PROCEDURE usegment(v){
	if (v < useg){
		uinf = 0
	}
}
