: Ion channel activation segregation -- Generated by BMTools (https://github.com/tjbanks/bmtools)
: based on the paper "Distinct Current Modules Shape Cellular Dynamics in Model Neurons" (2016)

NEURON {
	SUFFIX kaseg
	USEION k READ ek WRITE ik
	RANGE gbar, g
	RANGE ainf, atau, binf, btau
	RANGE ik
	RANGE avhalf, ak, aseg
} 

UNITS {
    (mA) =  (milliamp)
    (mV) =  (millivolt)
}
PARAMETER {
	gbar (siemens/cm2)
	avhalf = 27.2
	ak = -8.7
	aseg = -99
}

ASSIGNED {
    v (mV)
    ek (mV)
    ik (mA/cm2)
    ainf
    atau (ms)
    binf
    btau (ms)
    g (siemens/cm2)
}
STATE {
    a
    b
}
BREAKPOINT {
    SOLVE states METHOD cnexp
    g = gbar * a * a * a * b
    ik = g * (v - ek)
}
INITIAL {
    rate(v)
    a = ainf
    b = binf
}
DERIVATIVE states{
	rate(v)
	asegment(v)
	a' = (ainf - a) / atau
	b' = (binf - b) / btau
}

PROCEDURE rate(v){
	UNITSOFF
	ainf = 1.0 / (1.0 + (exp((v + avhalf) / (ak))))
	atau = (23.2 - 20.8 / (1 + (exp((v + 32.9) / (-15.2)))))
	binf = 1.0 / (1.0 + (exp((v + 56.9) / (4.9))))
	btau = (77.2 - 58.4 / (1.0 + (exp((v + 38.9) / (-26.5)))))
	UNITSON
}

: Segmentation functions

PROCEDURE asegment(v){
	if (v < aseg){
		ainf = 0
	}
}
