: Ion channel activation segregation -- Generated by BMTools (https://github.com/tjbanks/bmtools)
: based on the paper "Distinct Current Modules Shape Cellular Dynamics in Model Neurons" (2016)

NEURON {
	SUFFIX naseg
	USEION na READ ena WRITE ina
	RANGE gbar, g
	RANGE minf, hinf, mtau, htau
	RANGE ina
	RANGE mvhalf, mk, mseg
} 

UNITS {
    (mA) =  (milliamp)
    (mV) =  (millivolt)
}
PARAMETER {
	gbar (siemens/cm2)
	mvhalf = 25.5
	mk = -5.29
	mseg = -99
}

ASSIGNED {
    v (mV)
    ena (mV)
    ina (mA/cm2)
    minf
    hinf
    mtau (ms)
    htau (ms)
    g (siemens/cm2)
}
STATE {
    m
    h
}
BREAKPOINT {
    SOLVE states METHOD cnexp
    g = gbar * m * m * m * h
    ina = g * (v - ena)
}
INITIAL {
    rate(v)
    m = minf
    h = hinf
}
DERIVATIVE states{
	rate(v)
	msegment(v)
	m' = (minf - m) / mtau
	h' = (hinf - h) / htau
}

PROCEDURE rate(v){
	UNITSOFF
	minf = 1.0 / (1.0 + (exp((v + mvhalf) / (mk))))
	mtau = (2.64 - 2.52 / (1.0 + (exp((v + 120) / (-25)))))
	hinf = 1.0 / (1.0 + (exp((v + 48.9) / (5.18))))
	htau = (1.34 / (1 + (exp((v + 62.9) / (-10))))) * (1.5 + 1.0 / (1.0 + (exp((v + 34.9) / (3.6)))))
	UNITSON
}

: Segmentation functions

PROCEDURE msegment(v){
	if (v < mseg){
		minf = 0
	}
}
